### PR TITLE
Added Chainlink reference data contract for decentralized data

### PR DESCRIPTION
**Pull request by PatrickAlphaC**
Hi Jason! 
I added a simple reference data contract for you to test out. If you deploy this contract (If you deploy on remix you'll have to use the github.com/smartcontractkit/chainlink.... import instead of the npm @ syntax) you'll be able to get the price of ETH/USD. 

Just enter the aggregator address based on your testnet from here: https://docs.chain.link/docs/reference-contracts

Let me know if you have any questions! 

If you want to test it on remix, just compile the following code on solidity `v0.4.24` and deploy with the address on ropsten.
```
pragma solidity ^0.4.24;
import "github.com/smartcontractkit/chainlink/evm-contracts/src/v0.4/interfaces/AggregatorInterface.sol";
contract Demo {
    
    AggregatorInterface internal ref;
    // 0x8468b2bDCE073A157E560AA4D9CcF6dB1DB98507
    constructor(address _aggregator) public {
        ref = AggregatorInterface(_aggregator);
    }
    function getLatestPrice() public view returns (int256) {
        return ref.latestAnswer();
    }
}
```

### CODE REVIEW

**Comment by codenamejason** [comment]
How hard to do one for DAI as well?

**Comment by PatrickAlphaC** [comment]
It’s the exact same, just use the DAI/ETH contract from here:

https://docs.chain.link/docs/reference-contracts

**Comment by codenamejason** [comment]
Thank you so much bro, I can't tell you how much this helps me.

**Comment by PatrickAlphaC** [comment]
No problem. Feel free to ping me here, or join the chainlink discord. There’s always someone around to lend a hand.

https://discord.gg/2YHSAey

**Pull request merged**
